[package]
name = "validate_signature"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-primes = "0.3.0"
rug = "1.19.2"
sha3 = "0.10.8"
rand = "0.8.5"
ring = "0.16.20"
base64 = "0.20.0"
